### ISSUE TITLE
Incorrect connection

### ISSUE THREAD

**Issue by panther2** [triplea-maps/world_war_ii_v6_1941#3]
In line 297 of the game xml it says:

`<connection t1="42 Sea Zone" t2="Western Canada"/>`

However this is incorrect, as SZ42 is not adjacent to Western Canada.

Delete this line to fix this issue.

**Comment by RogerCooper** [comment]
I changed the XML. Please check that the commit worked.

**Comment by panther2** [comment]
Thank you @RogerCooper , I will check it as soon as possible, but not before next week when I will be back to my PC.

**Comment by panther2** [comment]
@RogerCooper Looks good! Thanks again!
